### ISSUE TITLE
Hello World | Tianma

### ISSUE THREAD

**Issue by tianma8023** [tianma8023/tianma8023.github.io#5]
http://tianma.pro/post/4a17b156/ 

 Everything will be okay in the end.

**Comment by tianma8023** [comment]
Which is your best favorite anim character from below list?
- Rem
- Sagiri
- Umaru
- Kaori

下面列表中的动漫角色你最喜欢哪个呢？
- 蕾姆
- 和泉·纱雾
- 土间·埋
- 宫园·薰

下面列表中的動漫角色你最喜歡哪個呢？
- 蕾姆
- 和泉·紗霧
- 土間·埋
- 宮園·薰

```java
    System.our.println("Hello World - Just for test");
```

> 斯巴魯，巴魯斯

**Comment by RemDaisuki** [comment]
> @tianma8023
> Which is your best favorite anim character from below list?
> - Rem
> - Sagiri
> - Umaru
> - Kaori
> 
> 下面列表中的动漫角色你最喜欢哪个呢？
> - 蕾姆
> - 和泉·纱雾
> - 土间·埋
> - 宫园·薰
> 
> 下面列表中的動漫角色你最喜歡哪個呢？
> - 蕾姆
> - 和泉·紗霧
> - 土間·埋
> - 宮園·薰
> 
> ```java
>     System.our.println("Hello World - Just for test");
> ```
> 
> > 斯巴魯，巴魯斯

当然是选蕾姆啦！
- Rem Daisuki
- Rem Daisuki
- Rem Daisuki

**Comment by RemDaisuki** [comment]
如果真爱有颜色，那么一定是蕾姆蓝！
